services:
  nginx:
    image: tnodecode/spineui-nginx
    ports:
      - 8080:80
    networks:
      - app
  streamlit:
    image: tnodecode/spineui
    ports:
      - 8501:8501
    volumes:
      - ./config:/app/config
      - ./datasets:/app/datasets
      - ./detections:/app/detections
      - ./training_metrics:/app/training_metrics
    networks:
      - app
  dash:
    image: tnodecode/spineui
    ports:
      - 8050:8050
    volumes:
      - ./config:/app/config
      - ./datasets:/app/datasets
      - ./detections:/app/detections
      - ./training_metrics:/app/training_metrics
    networks:
      - app
    command: ['python', 'app_dash.py']
  mmdet:
    image: tnodecode/spine-co-detr
    hostname: mmdet
    ports:
      - 8081:80
    volumes:
      - ./available_models.yml:/app/available_models.yml
      - ./models/mmcv:/app/runs
    networks:
      - app

networks:
  app:
    name: network_app
