services:
  nginx:
    image: tnodecode/spineui-nginx
    ports:
      - 8080:80
    networks:
      - app
  streamlit:
    image: tnodecode/spineui
    ports:
      - 8501:8501
    volumes:
      - ./config:/app/config
      - ./datasets:/app/datasets
      - ./detections:/app/detections
      - ./training_metrics:/app/training_metrics
    networks:
      - app
  dash:
    image: tnodecode/spineui
    ports:
      - 8050:8050
    volumes:
      - ./config:/app/config
      - ./datasets:/app/datasets
      - ./detections:/app/detections
      - ./training_metrics:/app/training_metrics
    networks:
      - app
    command: ['python', 'app_dash.py']
  yolo:
    image: tnodecode/yolo
    hostname: yolo
    ports:
      - 8081:80
    volumes:
      - ./models/yolov8x:/app/models
    networks:
      - app

networks:
  app:
    name: network_app
