datasets:
  - name: mot_train
    type: mot
    root_dir: ./datasets/MOT17_all/train
    paths:
      - ./datasets/MOT17_all/train/aid*/img/*.png
    detections:
      - name: Faster RCNN
        paths:
          - ./detections/faster_rcnn/faster_rcnn_mot_all_train_epoch_9.csv
    annotations:
      - name: mmtracking_train
        type: mmtracking
        paths: 
          - ./datasets/MOT17_all/annotations/train_cocoformat_all.json
      - name: trackformer_train
        type: trackformer
        paths: 
          - ./datasets/MOT17_all/annotations_trackformer/train.json
  - name: mot_val
    type: mot
    root_dir: ./datasets/MOT17_all/val
    paths:
      - ./datasets/MOT17_all/val/aid*/img/*.png
    stacks: 
      patterns:
        - regex: .*aid052N([0-9]{1})D([0-9]{1})_tp([0-9]{1,4})_stack([0-9]{1,4}).*
          stack_name: "aid052N$1D$2_tp$3_stack$4_default_aug_False_epoch_19_theta_0.5_delta_0.1_Test"
    annotations:
      - name: mmtracking_val
        type: mmtracking
        paths: 
          - ./datasets/MOT17_all/annotations/val_cocoformat_all.json
      - name: trackformer_val
        type: trackformer
        paths: 
          - ./datasets/MOT17_all/annotations_trackformer/val.json
  - name: mot_test
    type: mot
    root_dir: ./datasets/MOT17_all/test
    paths:
      - ./datasets/MOT17_all/test/aid*/img/*.png
    stacks: 
      patterns:
        - regex: .*aid052N([0-9]{1})D([0-9]{1})_tp([0-9]{1,4})_stack([0-9]{1,4}).*
          stack_name: "aid052N$1D$2_tp$3_stack$4_default_aug_False_epoch_19_theta_0.5_delta_0.1_Test"
    annotations:
      - name: mmtracking_test
        type: mmtracking
        paths: 
          - ./datasets/MOT17_all/annotations/test_cocoformat_all.json
      - name: trackformer_test
        type: trackformer
        paths: 
          - ./datasets/MOT17_all/annotations_trackformer/test.json
  - name: spine_mixed_train
    type: coco
    root_dir: ./datasets/spine/train
    paths:
      - ./datasets/spine/train/*.png
    stacks:
      patterns:
        - regex: .*aid052N([0-9]{1})D([0-9]{1})_tp([0-9]{1,4})_stack([0-9]{1,4})_layer([0-9]{1,4}).*
          stack_name: "aid052N$1D$2_tp$3_stack$4_default_aug_False_epoch_19_theta_0.5_delta_0.1_Test"
    annotations:
      - name: original
        type: coco
        paths: 
          - ./datasets/spine/annotations/instances_train2017.json
      - name: sam-b-bboxes-train
        type: coco
        paths: 
          - ./datasets/spine/annotations/train2017_sam_b.json
      - name: sam-b
        type: masks
        paths: 
          - ./datasets/spine/train-sam-b/*
      - name: sam-l
        type: masks
        paths: 
          - ./datasets/spine/train-sam-l/*
    detections:
      - name: Cascade RCNN
        paths:
          - ./detections/cascade_rcnn/cascade_rcnn_run*_spine_mixed_train.csv
      - name: Faster RCNN
        paths:
          - ./detections/faster_rcnn/faster_rcnn_run*_spine_mixed_train.csv
          - ./detections/cascade_rcnn/cascade_rcnn_run*_spine_mixed_train.csv
      - name: Co-DETR
        paths:
          - ./detections/co_detr_old/co_detr_co_dino_5scale_swin_large_16e_o365tococo_spine_mixed_epoch_*_train.csv
  - name: spine_mixed_val
    type: coco
    root_dir: ./datasets/spine/val
    paths:
      - ./datasets/spine/val/*.png
    stacks:
      patterns:
        - regex: .*aid052N([0-9]{1})D([0-9]{1})_tp([0-9]{1,4})_stack([0-9]{1,4})_layer([0-9]{1,4}).*
          stack_name: "aid052N$1D$2_tp$3_stack$4_default_aug_False_epoch_19_theta_0.5_delta_0.1_Test"
    annotations:
      - name: original
        type: coco
        paths: 
          - ./datasets/spine/annotations/instances_val2017.json
      - name: sam-b-bboxes-val
        type: coco
        paths: 
          - ./datasets/spine/annotations/val2017_sam_b.json
      - name: sam-b
        type: masks
        paths: 
          - ./datasets/spine/val-sam-b/*
      - name: sam-l
        type: masks
        paths: 
          - ./datasets/spine/val-sam-l/*
    detections:
      - name: Cascade RCNN
        paths:
          - ./detections/cascade_rcnn/cascade_rcnn_run*_spine_mixed_val.csv
      - name: Faster RCNN
        paths:
          - ./detections/faster_rcnn/faster_rcnn_run*_spine_mixed_val.csv
      - name: Co-DETR
        paths:
          - ./detections/co_detr_old/co_detr_co_dino_5scale_swin_large_16e_o365tococo_spine_mixed_epoch_*_val.csv
  - name: spine_mixed_test
    type: coco
    root_dir: ./datasets/spine/test
    paths:
      - ./datasets/spine/test/*.png
    stacks:
      patterns:
        - regex: .*aid052N([0-9]{1})D([0-9]{1})_tp([0-9]{1,4})_stack([0-9]{1,4})_layer([0-9]{1,4}).*
          stack_name: "aid052N$1D$2_tp$3_stack$4_default_aug_False_epoch_19_theta_0.5_delta_0.1_Test"
    annotations:
      - name: original
        type: coco
        paths: 
          - ./datasets/spine/annotations/instances_test2017.json
      - name: sam-b-bboxes-test
        type: coco
        paths: 
          - ./datasets/spine/annotations/test2017_sam_b.json
      - name: sam-b
        type: masks
        paths: 
          - ./datasets/spine/test-sam-b/*
      - name: sam-l
        type: masks
        paths: 
          - ./datasets/spine/test-sam-l/*
    detections:
      - name: Cascade RCNN
        paths:
          - ./detections/cascade_rcnn/cascade_rcnn_run*_spine_mixed_test.csv
      - name: Faster RCNN
        paths:
          - ./detections/faster_rcnn/faster_rcnn_run*_spine_mixed_test.csv
      - name: Co-DETR
        paths:
          - ./detections/co_detr_old/co_detr_co_dino_5scale_swin_large_16e_o365tococo_spine_mixed_epoch_*_test.csv
