datasets:
  - name: spine_tracking
    paths:
      - ./datasets/v853/220321/t1/*.png
      - ./datasets/v853/220321/t2/*.png
      - ./datasets/v853/220324/t1/*.png
      - ./datasets/v853/220324/t2/*.png
    annotations:
      - name: nonane
  - name: spine_mixed_train
    paths:
      - ./datasets/spine/train/*.png
    stacks:
      patterns:
        - regex: .*SR052N([0-9]{1})D([0-9]{1})day([0-9]{1})stack([0-9]{1}).*
          stack_name: "Simon N$1 D$2 day $3 stack $4"
        - regex: .*aidv853_date([0-9]{2})([0-9]{2})([0-9]{2})_tp([0-9]{1})_stack([0-9]{1})_sub([0-9]{2})_layer([0-9]{3}).*
          stack_name: "Altug $1-$2-$3 tp $4 stack $5 sub $6 layer $7"
    annotations:
      - name: original
        type: coco
        paths: 
          - ./datasets/spine/annotations/instances_train2017.json
      - name: sam-b-bboxes-train
        type: coco
        paths: 
          - ./datasets/spine/annotations/train2017_sam_b.json
      - name: sam-b
        type: masks
        paths: 
          - ./datasets/spine/train-sam-b/*
      - name: sam-l
        type: masks
        paths: 
          - ./datasets/spine/train-sam-l/*
    detections:
      - name: Cascade RCNN
        paths:
          - ./detections/cascade_rcnn/cascade_rcnn_run*_spine_mixed_train.csv
      - name: Faster RCNN
        paths:
          - ./detections/faster_rcnn/faster_rcnn_run*_spine_mixed_train.csv
          - ./detections/cascade_rcnn/cascade_rcnn_run*_spine_mixed_train.csv
      - name: Co-DETR
        paths:
          - ./detections/co_detr_old/co_detr_co_dino_5scale_swin_large_16e_o365tococo_spine_mixed_epoch_*_train.csv
  - name: spine_mixed_val
    paths:
      - ./datasets/spine/val/*.png
    annotations:
      - name: original
        type: coco
        paths: 
          - ./datasets/spine/annotations/instances_val2017.json
      - name: sam-b-bboxes-val
        type: coco
        paths: 
          - ./datasets/spine/annotations/val2017_sam_b.json
      - name: sam-b
        type: masks
        paths: 
          - ./datasets/spine/val-sam-b/*
      - name: sam-l
        type: masks
        paths: 
          - ./datasets/spine/val-sam-l/*
    detections:
      - name: Cascade RCNN
        paths:
          - ./detections/cascade_rcnn/cascade_rcnn_run*_spine_mixed_val.csv
      - name: Faster RCNN
        paths:
          - ./detections/faster_rcnn/faster_rcnn_run*_spine_mixed_val.csv
      - name: Co-DETR
        paths:
          - ./detections/co_detr_old/co_detr_co_dino_5scale_swin_large_16e_o365tococo_spine_mixed_epoch_*_val.csv
  - name: spine_mixed_test
    paths:
      - ./datasets/spine/test/*.png
    annotations:
      - name: original
        type: coco
        paths: 
          - ./datasets/spine/annotations/instances_test2017.json
      - name: sam-b-bboxes-test
        type: coco
        paths: 
          - ./datasets/spine/annotations/test2017_sam_b.json
      - name: sam-b
        type: masks
        paths: 
          - ./datasets/spine/test-sam-b/*
      - name: sam-l
        type: masks
        paths: 
          - ./datasets/spine/test-sam-l/*
    detections:
      - name: Cascade RCNN
        paths:
          - ./detections/cascade_rcnn/cascade_rcnn_run*_spine_mixed_test.csv
      - name: Faster RCNN
        paths:
          - ./detections/faster_rcnn/faster_rcnn_run*_spine_mixed_test.csv
      - name: Co-DETR
        paths:
          - ./detections/co_detr_old/co_detr_co_dino_5scale_swin_large_16e_o365tococo_spine_mixed_epoch_*_test.csv
  - name: spine_altug_train
    paths:
      - ./datasets/spine/train/aidv*.png
    annotations:
      - name: original
        type: coco
        paths: 
          - ./datasets/spine/annotations/instances_train2017.json
      - name: sam-b
        type: masks
        paths: 
          - ./datasets/spine/train-sam-b/aidv*
      - name: sam-l
        type: masks
        paths: 
          - ./datasets/spine/train-sam-l/aidv*
  - name: spine_altug_val
    paths:
      - ./datasets/spine/val/aidv*.png
    annotations:
      - name: original
        type: coco
        paths: 
          - ./datasets/spine/annotations/instances_val2017.json
      - name: sam-b
        type: masks
        paths: 
          - ./datasets/spine/val-sam-b/aidv*
      - name: sam-l
        type: masks
        paths: 
          - ./datasets/spine/val-sam-l/aidv*
  - name: spine_altug_test
    paths:
      - ./datasets/spine/test/aidv*.png
    annotations:
      - name: original
        type: coco
        paths: 
          - ./datasets/spine/annotations/instances_test2017.json
      - name: sam-b
        type: masks
        paths: 
          - ./datasets/spine/test-sam-b/aidv*
      - name: sam-l
        type: masks
        paths: 
          - ./datasets/spine/test-sam-l/aidv*
  - name: spine_simon_train
    paths:
      - ./datasets/spine/train/SR*.png
    annotations:
      - name: original
        type: coco
        paths: 
          - ./datasets/spine/annotations/instances_train2017.json
      - name: sam-b
        type: masks
        paths: 
          - ./datasets/spine/train-sam-b/SR*
      - name: sam-l
        type: masks
        paths: 
          - ./datasets/spine/train-sam-l/SR*
  - name: spine_simon_val
    paths:
      - ./datasets/spine/val/SR*.png
    annotations:
      - name: original
        type: coco
        paths: 
          - ./datasets/spine/annotations/instances_val2017.json
      - name: sam-b
        type: masks
        paths: 
          - ./datasets/spine/val-sam-b/SR*
      - name: sam-l
        type: masks
        paths: 
          - ./datasets/spine/val-sam-l/SR*
  - name: spine_simon_test
    paths:
      - ./datasets/spine/test/SR*.png
    annotations:
      - name: original
        type: coco
        paths: 
          - ./datasets/spine/annotations/instances_test2017.json
      - name: sam-b
        type: masks
        paths: 
          - ./datasets/spine/test-sam-b/SR*
      - name: sam-l
        type: masks
        paths: 
          - ./datasets/spine/test-sam-l/SR*